log_dir: "results/loop"
quad_name: "hummingbird"
verbose: False
seq_len: 1 # History Lenght. When increasing to more than one, the model becomes machine dependent due to data saving latency.
checkpoint:
  # Put to true and add a path for loading a ckpt
  resume_training: False
  resume_file: ""
data_generation:
  max_rollouts: 150
  train_every_n_rollouts: 30
  double_th_every_n_rollouts: 30
train:
  max_training_epochs: 20
  max_allowed_error: 0.6 # Collision rollouts are eliminated from the training
  min_number_fts: 40 # Number of feature tracks per image
  batch_size: 32
  summary_freq: 400
  train_dir: "data/loop/train" # Where data will be generated and where the network will train
  val_dir: "data/loop/test" # Validation Data, change to a new data folder!
  save_every_n_epochs: 5
  use_imu: True
  use_fts_tracks: True
test_time:
  execute_nw_predictions: True
  # Dagger constants and random controller constants for exploration
  fallback_threshold_rates: 1.0
  rand_thrust_mag: 6
  rand_rate_mag: 3.5
  rand_controller_prob: 0.05

